### ISSUE TITLE
Create admin front-end page

### ISSUE THREAD

**Issue by ryosuzuki** [juanm95/ryotwilio#1]
Create admin view 

Estimation time: 1day
1. Create admin controller 
2. Change `route.rb` to `/admin => admin/index.html`
3. Create `admin/index.html` in admin view 
4. Write HTML/CSS code on `admin/index.html` with Bootstrap 
5. Replicate this 

![](http://activeadmin.info/images/features.png)

**Comment by juanm95** [comment]
What is the desired functionality for buttons, links, and dropdowns?

**Comment by juanm95** [comment]
Should I try to exactly copy the image or is the goal to simply replicate the UI using the base bootstrap styling?

**Comment by ryosuzuki** [comment]
Close 99309c6
